---
- name: Build k8s master
  hosts: master
  gather_facts: false
  roles:
      - { role: master }

- name: Build k8s nodes
  hosts: node
  gather_facts: false
  roles:
        - { role: overlay}
        - { role: node }



